[project]
name = "NLGCG"
version = "2026.0.0"
requires-python = ">=3.11"
authors = [
  { name = "Arsen Hnatiuk", email = "arsen.hnatiuk@hu-berlin.de" },
  { name = "Konstantin Pieper", email = "konstpieper@web.de" },
  ]
readme = "README.md"
dependencies = [
  "numpy",
  "scipy",
  "jax"
]

[project.optional-dependencies]
tests = [
  "cvxpy",
  "matplotlib",
]



